// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3ym5i0U5ZqJjNUfRlDM5fet1y540yBRA',
    appId: '1:474193681656:web:248654245fdf008759ef0d',
    messagingSenderId: '474193681656',
    projectId: 'virtual-trading-app-d0ab1',
    authDomain: 'virtual-trading-app-d0ab1.firebaseapp.com',
    storageBucket: 'virtual-trading-app-d0ab1.firebasestorage.app',
    measurementId: 'G-N648MCNR6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVl96PH2nemhVoLKSAHQmUg_Y2kEffFfQ',
    appId: '1:474193681656:android:7a2b5bc5e7527e0f59ef0d',
    messagingSenderId: '474193681656',
    projectId: 'virtual-trading-app-d0ab1',
    storageBucket: 'virtual-trading-app-d0ab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbjoHt2sqIU8aD2p0yjzW5rsYRB0zZIHs',
    appId: '1:474193681656:ios:0cd9119ae3a2c94e59ef0d',
    messagingSenderId: '474193681656',
    projectId: 'virtual-trading-app-d0ab1',
    storageBucket: 'virtual-trading-app-d0ab1.firebasestorage.app',
    iosBundleId: 'com.example.virtualTradingApp',
  );
}
